# Generated by Django 5.2.7 on 2025-10-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
